theme: jekyll-theme-minimal
# title: Decomply (!) - AI Software Decomposer
description: Fast, structured, and effortless.
logo: /assets/img/decomply-logo.png # Update this path if you add a logo
show_downloads: false 